# Site settings
title: Klackbergsgården
description: En oas i Bergslagens hjärta
url: https://jdahlborg.github.io # the base hostname & protocol, e.g. http://example.com
baseurl: /klackbergsgarden # the subpath of your site, e.g. /blog
permalink: pretty

formspree_booking_form_id: xlddydzo  # Formspree booking form ID
formspree_contact_form_id: xgvvjojn  # Formspree contact form ID

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore

# Contact information
contact:
  email: info@klackbergsgarden.se
  phone: +46 (0)223-220 33
  address: Klackbergsvägen 103, 738 91 Norberg 
